import sqlite3
conn = sqlite3.connect('Lection 7.db')
cursor = conn.cursor()
# cursor.execute("SELECT Имя FROM Лекция ORDER BY Имя LIMIT 2")
# results = cursor.fetchall()
# cursor.execute("INSERT into Лекция values (123, 'ТЩт','None', 'None') ")
# cursor.execute("INSERT into Лекция(Имя) values (123) ")
# conn.commit()
# print(results)
cursor.execute('CREATE TABLE category (Тапки TEXT,Самолеты TEXT, Ноутбуки TEXT )')
cursor.execute('CREATE TABLE product (Имя TEXT,Цена NUMERIC,Категории REFERENCES category(rowid))')
cursor.execute("INSERT INTO product (Имя, Цена, Категории) VALUES ('Босоножки', 1.17, 1),('Вьетнамки', 2.36, 1),('Макасины', 4.99, 1),('ИЛ-2', 556000, 2),('Суперджет 100', 1500000, 2),('Ту-160', 25000000, 2),('Dell', 590, 3),('Lenovo', 200, 3),('Sony', 437, 3)")
cursor.execute('ALTER TABLE product ADD Размер INTEGER')
cursor.execute('ALTER TABLE product ADD Вместимость INTEGER')
cursor.execute('ALTER TABLE product ADD Процессор TEXT')
conn.commit()
conn.close()